on: [ pull_request ]

name: ChatGPT CodeReview


jobs:
  chatgpt_comment:
    runs-on: self-hosted
    name: Let chatgpt comment on your PR.
    steps:
      - name: Create annotation for build error
        run: echo "token crap $SESSION_TOKEN  $crap"
      - name: ChatGPT comment
        uses: kxxt/chatgpt-action@v0.3
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: ${{ secrets.CHATGPT_SESSION_TOKEN }}
          split: 'yolo'  # Use true to enable the unstable split feature.
        env:
          SESSION_TOKEN: ${{ secrets.CHATGPT_SESSION_TOKEN }}
          CRAP: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
